apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: {{ .Values.postgres.serviceName }}
    app: {{ .Values.appName }}
spec:
  selector:
    name: {{ .Values.postgres.podName }}
    app: {{ .Values.appName }}
  ports:
  - port: 5432
    targetPort: 5432
