apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.deployName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.postgres.podName }}
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.postgres.podName }}
      labels:
        name: {{ .Values.postgres.podName }}
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.name}}:{{ .Values.postgres.image.tag}}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
