apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.deployName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.postgres.podName }}
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.postgres.podName }}
      labels:
        name: {{ .Values.postgres.podName }}
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.name}}:{{ .Values.postgres.image.tag}}"
        resources:
          limits:
            memory: {{ .Values.postgres.containerMemory }}
            cpu: {{ .Values.postgres.containerCPU }}
          requests:         
            memory: {{ .Values.postgres.containerMemory }}
            cpu: {{ .Values.postgres.containerCPU }}
        # Environment variables for PostgreSQL  
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
