apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.deployName }}
  namespace: {{ .Values.namespace }}  
  labels:
    name: {{ .Values.redis.deployName }}
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.redis.podName }}
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.redis.podName }}    
      labels:
        name: {{ .Values.redis.podName }}
        app: {{ .Values.appName }}  
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.containerImage }}"
        resources:
          limits:
            memory: {{ .Values.redis.containerMemory }}
            cpu: {{ .Values.redis.containerCPU }}
          requests:
            memory: {{ .Values.redis.containerMemory }}
            cpu: {{ .Values.redis.containerCPU }}
        ports:
          - containerPort: 6379
