apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: {{ .Values.redis.serviceName }}
    namespace: {{ .Values.namespace }}
    app: {{ .Values.appName }}
spec:
  selector:
    name: {{ .Values.redis.podName }}
    app: {{ .Values.appName }}  
  ports:
  - port: 6379
    targetPort: 6379
