apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resultapp.deployName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.resultapp.deployName }}
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.resultapp.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.resultapp.podName }}
      app: {{ .Values.appName }}  
  template:
    metadata:
      name: {{ .Values.resultapp.podName }}    
      labels:
        name: {{ .Values.resultapp.podName }}
        app: {{ .Values.appName }}  
    spec:
      containers:
      - name: result-app
        image: {{ .Values.resultapp.containerImage }}
        resources:
          limits:
            memory: {{ .Values.resultapp.containerMemory }}
            cpu: {{ .Values.resultapp.containerCPU }}
          requests:
            memory: {{ .Values.resultapp.containerMemory }}
            cpu: {{ .Values.resultapp.containerCPU }}
        ports:
          - containerPort: {{ .Values.resultapp.containerPort }}
