apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resultapp.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.resultapp.podName }}
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.resultapp.type }}
  selector:
    name: {{ .Values.resultapp.podName }}
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.resultapp.containerPort }}
    targetPort: {{ .Values.resultapp.containerPort }}
    nodePort: {{ .Values.resultapp.nodePort }}
