apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.deployName }}
  namespace: {{ .Values.namespace }}   
  labels:
    name: {{ .Values.worker.deployName }}
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
        name: {{ .Values.worker.podName }}
        app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.worker.podName }}
      labels:
        name: {{ .Values.worker.podName }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: worker-app
          image: {{ .Values.worker.containerImage }}
          resources:
            limits:
              memory: {{ .Values.worker.containerMemory }}
              cpu: {{ .Values.worker.containerCPU }}
            requests:
              memory: {{ .Values.worker.containerMemory }}
              cpu: {{ .Values.worker.containerCPU }}  

