apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod    
  labels:
    name: result-app-pod
    app: demo-voting-app  
spec:
  containers:
  - name: result-app
<<<<<<< HEAD
    image: kodekloud/examplevotingapp_result:v1
    resources:
=======
    image: dockersamples/examplevotingapp_result
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"  
>>>>>>> fdf72f7 (changes to with-deployment)
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
