apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod    
  labels:
    name: result-app-pod
    app: demo-voting-app  
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"  
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
