apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
<<<<<<< HEAD
      image: kodekloud/examplevotingapp_worker:v1
      resources:
=======
      image: dockersamples/examplevotingapp_worker     
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
>>>>>>> fdf72f7 (changes to with-deployment)
        limits:
          memory: "128Mi"
          cpu: "500m"
