apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: result-app-pod
    app: demo-voting-app
  ports:
<<<<<<< HEAD
  - port: 80
    targetPort: 80
    nodePort: 30005
=======
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30002
>>>>>>> fdf72f7 (changes to with-deployment)
